# Generated by Django 6.0 on 2026-01-05 10:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['target_date'], 'verbose_name': 'Запись календаря', 'verbose_name_plural': 'Записи календаря'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_dates',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='check_out_after_check_in',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='at_least_one_guest',
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('listing', 'target_date')},
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lessee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за ночь'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending (wait)'), ('confirmed', 'confirmed by lessor'), ('active', 'active'), ('cancelled', 'cancelled by lessee'), ('completed', 'completed'), ('rejected', 'rejected by lessor')], default='pending', max_length=20, verbose_name='Статус бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='booking.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('archived', 'archived'), ('rented', 'rented')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='time_slot',
        ),
    ]
