# Generated by Django 6.0 on 2026-01-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_calendar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country']},
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
