# Generated by Django 6.0 on 2026-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_address_options_alter_address_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Germany', max_length=100, verbose_name='Страна'),
        ),
    ]
